spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/controle-financeiro # Substitua com o nome do seu banco de dados
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Isso permitirá que o Hibernate crie/atualize a tabela
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    jpa:
      auditing:
        enabled: true # Habilita a auditoria JPA
